USE [MunITCR]
GO

SELECT * FROM [CCArregloPago]  
SELECT * FROM [CCBasura]  
SELECT * FROM [CCConsumoAgua]  
SELECT * FROM [CCImpuestoPropiedad]  
SELECT * FROM [CCInteresMoratorio]  
SELECT * FROM [CCMantenimientoParque]  
SELECT * FROM [CCPatenteComercial]  
SELECT * FROM [CCReconexion]  
SELECT * FROM [ComprobantePago]  
SELECT * FROM [ConceptoCobro]  
SELECT * FROM [DetalleCC]  
SELECT * FROM [DetalleCCArregloPago]  
SELECT * FROM [DetalleCCConsumoAgua]  
SELECT * FROM [EntityType]  
SELECT * FROM [ErrorLog] ORDER BY [ErrorDateTime] DESC 
SELECT * FROM [EventLog] ORDER BY [DateTime] DESC  
SELECT * FROM [EventType]  
SELECT * FROM [Factura]  
SELECT * FROM [MedioPago]  
SELECT * FROM [MovimientoArregloPago]  
SELECT * FROM [MovimientoConsumoAgua]  
SELECT * FROM [OrdenCorte]  
SELECT * FROM [OrdenReconexion]  
SELECT * FROM [Parametro]  
SELECT * FROM [ParametroInteger]    
SELECT * FROM [PeriodoMontoCC]  
SELECT * FROM [Persona]  
SELECT * FROM [PersonaXPropiedad]  
SELECT * FROM [Propiedad]  
SELECT * FROM [PropiedadXCCArregloPago]  
SELECT * FROM [PropiedadXCCConsumoAgua]  
SELECT * FROM [PropiedadXConceptoCobro]  
SELECT * FROM [TasaInteres]  
SELECT * FROM [TipoDocIdentidad]  
SELECT * FROM [TipoMontoCC]  
SELECT * FROM [TipoMovimientoArregloPago]  
SELECT * FROM [TipoMovimientoConsumoAgua]  
SELECT * FROM [TipoParametro]  
SELECT * FROM [TipoUsoPropiedad]  
SELECT * FROM [TipoZonaPropiedad]  
SELECT * FROM [Usuario]  
SELECT * FROM [UsuarioXPropiedad]  
